### PR TITLE
Tarpit & customizable redirections

### PR DESCRIPTION
**Pull request by yormy**
1) Tarpit implementation 
2) Added configurable views/routes per middleware

### CODE REVIEW

**Comment by yormy** [comment]
I hope you like it

**Comment by denisdulici** [comment]
Unfortunately, can't merge this because:

1- response/redirection related changes must be a separate PR
2- time-based blocking must be applicable for all middleware, not only IP

Feel free to resubmit the changes.

**Comment by yormy** [comment]
Ok,
Can you please elaborate on your 1 and 2, I do not understand completely what you mean
1) You mean the config changes need to be a separate PR ?
2) I have no clue what you mean or what to change

**Comment by zgelici** [comment]
@denisdulici 

Can you explain it better?

**Comment by yormy** [comment]
Please assist me make this PR better so you can merge it... What do I need to clarify ?

**Pull request closed without merging**
